### ISSUE TITLE
Unable to figure out how to set openapi config in angular

### ISSUE THREAD

**Issue by deefdragon** [cryptodev1990/openapi-typescript-codegen#20]
I have a service getting generated in the angular format via
```
npx openapi-typescript-codegen \
--input ./project/openapi.yaml \
--output src/app/gen/services/project \
--name project \
--postfix Service \
-c angular
```
but I need to change the openAPI object (specifically BASE)., but I have been unable to find a way to do so.

I can import the service and use it in any component that I need, but the issue is that I am unable to set the base URL for my development environment.

Is this something that is currently possible? 

this is my current NGModule.
```js
@NgModule({
	declarations: [/*..some Components*/],
	imports: [
		RouterModule.forChild(routes),
		CommonModule,
		FontAwesomeModule,
		StandardButtonsModule,
		SharedModule,
		StandardInputsModule,
		project,
	],
	providers: [],
})
export class FanfareModule {
}
```

**Comment by cryptodev1990** [comment]
I guess we have to substract above problems
